import type { NpmAuditReport } from "./npm-audit-report";

/** Default moderate sample — small SaaS dashboard project */
export const sampleNpmAudit: NpmAuditReport = {
  auditReportVersion: 2,
  runId: "demo-sample-2026-default",
  metadata: {
    vulnerabilities: { critical: 1, high: 4, moderate: 8, low: 12, info: 3 },
    dependencies: 412,
    devDependencies: 687,
    optionalDependencies: 18,
    peerDependencies: 44,
    totalDependencies: 1161,
  },
  advisories: {
    "1100001": {
      id: 1100001,
      module_name: "lodash",
      severity: "critical",
      title: "Prototype Pollution in lodash",
      overview: "Deep merge operations may mutate Object.prototype when processing attacker-controlled keys.",
      recommendation: "Upgrade lodash to 4.17.21 or later.",
      patched_versions: ">=4.17.21",
      url: "https://github.com/advisories/GHSA-demo-lodash",
      cves: ["CVE-2026-10001"],
      cwe: ["CWE-1321"],
      cvss: { score: 9.1 },
      findings: [{ version: "4.17.19", paths: ["admin-ui>lodash", "shared-utils>lodash"] }],
    },
    "1100002": {
      id: 1100002,
      module_name: "express",
      severity: "high",
      title: "Open redirect in express.static",
      overview: "Malformed paths may redirect users to external domains.",
      recommendation: "Upgrade express.",
      patched_versions: ">=4.21.0",
      cves: ["CVE-2026-10002"],
      cvss: { score: 7.5 },
      findings: [{ version: "4.18.2", paths: ["api-server>express"] }],
    },
    "1100003": {
      id: 1100003,
      module_name: "webpack-dev-server",
      severity: "high",
      title: "Source code exposure via WebSocket",
      overview: "Development server may leak source maps to unauthenticated clients.",
      recommendation: "Upgrade webpack-dev-server and restrict dev server access.",
      patched_versions: ">=5.2.0",
      cvss: { score: 7.8 },
      findings: [{ version: "4.15.1", paths: ["admin-ui>webpack-dev-server"] }],
    },
    "1100004": {
      id: 1100004,
      module_name: "minimatch",
      severity: "moderate",
      title: "Regular Expression Denial of Service",
      overview: "Crafted glob patterns may cause excessive backtracking.",
      recommendation: "Upgrade minimatch.",
      patched_versions: ">=5.1.6",
      cvss: { score: 5.3 },
      findings: [{ version: "3.0.4", paths: ["jest>micromatch>minimatch"] }],
    },
    "1100005": {
      id: 1100005,
      module_name: "postcss",
      severity: "moderate",
      title: "Parser hang on malformed CSS",
      overview: "Malformed comments can trigger high CPU during parsing.",
      recommendation: "Upgrade postcss.",
      patched_versions: ">=8.4.39",
      cvss: { score: 5.5 },
      findings: [{ version: "8.4.31", paths: ["tailwindcss>postcss"] }],
    },
  },
  actions: [
    {
      action: "update",
      module: "lodash",
      target: "4.17.21",
      resolves: [
        { id: 1100001, path: "admin-ui>lodash", dev: true },
        { id: 1100001, path: "shared-utils>lodash", dev: false },
      ],
    },
    {
      action: "update",
      module: "express",
      target: "4.21.0",
      resolves: [{ id: 1100002, path: "api-server>express", dev: false }],
    },
    {
      action: "install",
      module: "webpack-dev-server",
      target: "5.2.0",
      isMajor: true,
      resolves: [{ id: 1100003, path: "admin-ui>webpack-dev-server", dev: true }],
    },
    {
      action: "update",
      module: "minimatch",
      target: "5.1.6",
      resolves: [{ id: 1100004, path: "jest>micromatch>minimatch", dev: true }],
    },
    {
      action: "update",
      module: "postcss",
      target: "8.4.39",
      resolves: [{ id: 1100005, path: "tailwindcss>postcss", dev: true }],
    },
  ],
  muted: [],
};

export const sampleNpmAuditJson = JSON.stringify(sampleNpmAudit, null, 2);
